import Head from "next/head";
import { client } from "@sanity/lib/client";

// Import Components
import Header from "@src/components/Header/Header";
import Benefits from "@src/components/Benefits/Benefits";
import ImageText from "@src/components/ImageText/ImageText";
import Cardapio from "@src/components/Cardapio/Cardapio";
import Reviews from "@src/components/Reviews/Reviews";
import Menu from "@src/components/Menu/Menu";
import Footer from "@src/components/Footer/Footer";
import Navbar from "@src/components/Navbar/Navbar";

export default function Home({
  header,
  benefits,
  about,
  cardapio,
  reviews,
  location,
  menu,
  footer,
}) {
  return (
    <>
      <Head>
        <title>Minhas Massas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Header header={header} />
      <main>
        <Benefits benefits={benefits} />
        <ImageText data={about} id="about" />
        <Cardapio cardapio={cardapio} />
        <Reviews reviews={reviews} />
        <ImageText data={location} id="location" />
        <Menu menu={menu} />
      </main>
      <Footer footer={footer} />
    </>
  );
}

// Export Get Static Props
export const getStaticProps = async () => {
  const header = await client.fetch(`*[_type == "header"][0]`);
  const benefits = await client.fetch(`*[_type == "benefits"][0..2]`);
  const about = await client.fetch(`*[_type == "about"][0]`);
  const cardapio = await client.fetch(`*[_type == "cardapio"][0..3]`);
  const reviews = await client.fetch(`*[_type == "reviews"][0..2]`);
  const location = await client.fetch(`*[_type == "location"][0]`);
  const menu = await client.fetch(`*[_type == "menu"][0..19]`); // Limitando os 20 primeiros
  const footer = await client.fetch(`*[_type == "footer"][0]`);

  return {
    props: {
      header,
      benefits,
      about,
      cardapio,
      reviews,
      location,
      menu,
      footer,
    },
    revalidate: 60,
  };
};
